#!/usr/bin/env python

from argparse import ArgumentParser, REMAINDER
from subprocess import call

argparse = ArgumentParser(description = "Project 128 - Project Manager")

argparse.add_argument("-v", "--version", action = "version", version = "${VERSION}")

argparse.add_argument("script", help = "script to execute")
argparse.add_argument("args", help = "arguments to execute script with", nargs = REMAINDER)

args = argparse.parse_args()

exit(call([ "bash", "-c", "source .proj128 && " + args.script + " \"" + "\" \"".join(args.args) + "\"" ]))
