#!/usr/bin/env bash

if [ ! -f "/dev/stdin" ]
then
    echo "No tests passed via stdin!"
    exit 1
fi

tests=0
success=0

while read test
do
    let tests++
    
    echo "> $test"
    if eval "$test"
    then
        let success++
        echo "==> true"
    else
        echo "==> false"
    fi
done

echo ""
if [ $tests -eq $success ]
then
    echo "All ($tests) tests executed successfull!"
else
    echo "$success/$tests test(s) executed successfull!"
    echo "$(($tests - $success)) test(s) failed!"
    exit 1
fi
